name       : parley
version    : 18.08.1
release    : 15
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.1/src/parley-18.08.1.tar.xz : 1948f640022ca9241e23b7deb100ed68085fbaf96aebe04eb1e3898a0d4092af
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop
summary    : Parley is a vocabulary trainer
description: |
    Parley is a vocabulary trainer. It helps you to memorize your vocabulary, for example when you are trying to learn a foreign language. It supports many language specific features, but can be used for other learning tasks as well. It uses the spaced repetition learning method, which makes learning optimal. Vocabulary collections can be downloaded by "Get Hot New Stuff" or created with the built-in editor.
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - kross-devel
    - kxmlgui-devel
    - libkeduvocdocument-devel
    - sonnet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
