name       : parley
version    : 19.04.1
release    : 23
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.1/src/parley-19.04.1.tar.xz : c52746417d32e31f66c1165fd08ab87696d5ef4b5a020a175fe00e60474bc73f
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop
summary    : Parley is a vocabulary trainer
description: |
    Parley is a vocabulary trainer. It helps you to memorize your vocabulary, for example when you are trying to learn a foreign language. It supports many language specific features, but can be used for other learning tasks as well. It uses the spaced repetition learning method, which makes learning optimal. Vocabulary collections can be downloaded by "Get Hot New Stuff" or created with the built-in editor.
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - kross-devel
    - kxmlgui-devel
    - libkeduvocdocument-devel
    - sonnet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
