name       : parley
version    : 18.04.2
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.2/src/parley-18.04.2.tar.xz : 1b02f7a710d1a08a605978e0549ecf732ea8d17130465237760f208827596a31
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop
summary    : Parley is a vocabulary trainer
description: |
    Parley is a vocabulary trainer. It helps you to memorize your vocabulary, for example when you are trying to learn a foreign language. It supports many language specific features, but can be used for other learning tasks as well. It uses the spaced repetition learning method, which makes learning optimal. Vocabulary collections can be downloaded by "Get Hot New Stuff" or created with the built-in editor.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - kross-devel
    - kxmlgui-devel
    - libkeduvocdocument-devel
    - sonnet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
