name       : parley
version    : 22.08.3
release    : 63
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/parley-22.08.3.tar.xz : 7b866d43d2013b0047dc19b86012c89484d06f8531fe0ec324b164b546963dc1
homepage   : https://kde.org/applications/education/org.kde.parley
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop
summary    : Parley is a vocabulary trainer
description: |
    Parley is a vocabulary trainer. It helps you to memorize your vocabulary, for example when you are trying to learn a foreign language. It supports many language specific features, but can be used for other learning tasks as well. It uses the spaced repetition learning method, which makes learning optimal. Vocabulary collections can be downloaded by "Get Hot New Stuff" or created with the built-in editor.
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - kcmutils-devel
    - kcrash-devel
    - kdoctools-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - ktextwidgets-devel
    - libkeduvocdocument-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
