name       : parley
version    : 20.04.1
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.1/src/parley-20.04.1.tar.xz : 60dfe90d58adc9b64354073a0abb54ce0f65fc51fc6d18201636ac4b58fe67b8
homepage   : https://kde.org/applications/education/org.kde.parley
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop
summary    : Parley is a vocabulary trainer
description: |
    Parley is a vocabulary trainer. It helps you to memorize your vocabulary, for example when you are trying to learn a foreign language. It supports many language specific features, but can be used for other learning tasks as well. It uses the spaced repetition learning method, which makes learning optimal. Vocabulary collections can be downloaded by "Get Hot New Stuff" or created with the built-in editor.
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - kcmutils-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdoctools-devel
    - knewstuff-devel
    - knotifications-devel
    - kross-devel
    - kwindowsystem-devel
    - libkeduvocdocument-devel
    - sonnet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc