name       : parley
version    : 19.08.1
release    : 27
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/parley-19.08.1.tar.xz : 6ee4d538ddaecd5b6c3d855db62a4b5061240b2089b3dcc592712398fd1d066b
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop
summary    : Parley is a vocabulary trainer
description: |
    Parley is a vocabulary trainer. It helps you to memorize your vocabulary, for example when you are trying to learn a foreign language. It supports many language specific features, but can be used for other learning tasks as well. It uses the spaced repetition learning method, which makes learning optimal. Vocabulary collections can be downloaded by "Get Hot New Stuff" or created with the built-in editor.
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - kcmutils-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdoctools-devel
    - knewstuff-devel
    - knotifications-devel
    - kross-devel
    - libkeduvocdocument-devel
    - sonnet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
